services:
  - type: web
    name: hwll-api
    runtime: node
    rootDir: backend
    buildCommand: apt-get install -y poppler-utils && npm install && npm run build
    startCommand: npm start
    envVars:
      - key: PORT
        value: 10000
    plan: free
